// <auto-generated />
namespace Assignment8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedartisttomediaasset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedartisttomediaasset));
        
        string IMigrationMetadata.Id
        {
            get { return "201604052113181_added-artist-to-media-asset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
